### ISSUE TITLE
Missing env instructions

### ISSUE THREAD

**Issue by MoMannn** [KILTprotocol/nextjs-sporran-credential-login#2]
From what I gather trying to set this up its missing some instructions on how to set an .env file for the server side to work.

<img width="942" alt="Screenshot 2022-06-07 at 16 12 22" src="https://user-images.githubusercontent.com/8865298/172402325-ee70835a-5495-48f4-a738-647467c5f4ca.png">

It would be helpful to add an .env example or instructions on how to properly set it up.

**Comment by Dudleyneedham** [comment]
@MoMannn I have added instructions to the readme. Does this handle the issue?
